apiVersion: v1
kind: ServiceAccount
metadata:
  name: stress-analyzer
  namespace: svastik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stress-analyzer-deployer
  namespace: svastik
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stress-analyzer-deployer
  namespace: svastik
subjects:
  - kind: ServiceAccount
    name: stress-analyzer
    namespace: svastik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stress-analyzer-deployer
